<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>msg_requiredPassword</name>
   <tag></tag>
   <elementGuidId>4f678cd3-34fa-4bf6-9634-f25196d1bc88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@name='password']/../../span[text()='Required']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name='password']/../../span[text()='Required']</value>
      <webElementGuid>cfabbfcc-b26d-4275-94d8-ed71db13ed58</webElementGuid>
   </webElementProperties>
</WebElementEntity>
