<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mnu_dashboard</name>
   <tag></tag>
   <elementGuidId>029cb279-f0e9-4e54-874c-6e51b88086f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[contains(@href,'/web/index.php/dashboard/index')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[contains(@href,'/web/index.php/dashboard/index')]</value>
      <webElementGuid>ae8a852c-1b92-4638-b057-e1998d360ff6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
